model:
  # num_classes: 115 
  emb_size: 512
  dropout: 0.4
  batchnorm: False
  backbone: "resnet18"

data:
  bs: 256 
  nw: 8

training:
  lr: 0.0003
  num_epochs: 20 
  num_batches: 1024
  ckpt_interval: 1
  log_interval: 1
  resume: False
