model:
  emb_size: 512 
  dropout: 0.4
  batchnorm: False

data:
  bs: 256 
  nw: 8 
  sampler: weighted
  transforms: ["colorrand", "crop"]
  maxlen: 32 
  suffix: ioumf

training:
  lr: 0.0001
  num_epochs: 200 
  num_batches: 1024
  log_interval: 1
  ckpt_interval: 1
  resume: False 