model:
  emb_size: 512 
  dropout: 0.4
  batchnorm: False 
  backbone: "resnet18"

data:
  bs: 256 
  nw: 8
  sampler: weighted
  maxlen: 100
  minlen: 0
  suffix: ioumf
  tcn: False
  # crop: random

training:
  lr: 0.0001
  num_epochs: 200
  num_batches: 512 
  log_interval: 1
  ckpt_interval: 10
  resume: False
  # resume_name: 'checkpoint_last.pth'
