model:
  backbone: "resnet50"
  avg_output: True 
  is_sym: False # If the encoder and decoder are symmetric

data:
  bs: 64
  nw: 16
  imsize: 128
  contact: True # Default True
  EPIC55_only: True
  data_dir: /home/mohit/EPIC-KITCHENS
  # annot_dir: /home/mohit/VOS/epic-affordances/training/scripts/generate_metadata
  annot_dir: /home/mohit/VOS/epic-affordances/training/scripts/generate_metadata/nosup
  hand_seg_dir: /data02/mohit/VOS/video-hand-grasps/src_segmentation/inferred_masks/epic/SegNetFCNMultiHead_Egohandsfull

training:
  lr: 0.0001
  decay: 0.0001
  num_epochs: 400
  num_batches: 256
  save_after: 10 # num_valsteps
  replace: False
  log_interval: 1
  ckpt_interval: 5
  resume: False
  pos_weight: 4
  flips: True # Default True
  motionblur: True # Default True
  negres_fixed: False # Default False
  hand_mask: True # Default True
  obj_mask: True # Default True
  obj_sample: True # Default True
  obj_thresh: 0.8 # Default 0.8
  length_based_sampling: True # Default True
  masking: True # Default True
  bbshift: 0. # Default 0.
  mask_location: bc # Default bc
  use_no_hands: True # Default False
  use_hand_segmask: False # Default False