data:
  bs: 256
  nw: 2
  filter: {'object': [carrot, potato, knife, spoon, fork, fridge, microwave/oven, drawer, bottle, jar, cupboard, egg, onion]}
  filter_train: {'object': [fridge, drawer, jar, egg, carrot, potato, knife]}
  filter_eval: {'object': [cupboard, microwave/oven, onion, bottle, spoon, fork]}

training:
  decay: 0.001
  num_epochs: 25
  num_batches: 10
  replace: True
  log_interval: 1
  ckpt_interval: 1
  resume: False
  # sample_opposite: 1

model:
  emb_size: 512

